asd2asd223324asfff2f

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,20 +1,16 @@
 name: "Terraform action"
-
 on:
   push:
     branches:
-      -main
+      - main
   pull_request:
-
 permissions:
       id-token: write # This is required for aws oidc connection
       contents: read # This is required for actions/checkout
       pull-requests: write # This is required for gh bot to comment PR
-
 env:
   TF_LOG: INFO
   AWS_REGION: ${{ secrets.AWS_REGION }}
-
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -25,74 +21,41 @@ jobs:
     steps:
       - name: Git checkout
         uses: actions/checkout@v3
-      
-      - name: Verificar longitud del secreto
-        run: |
-          echo "${AWS_REGION:0:8}"
-          echo "${AWS_ACCESS_KEY_ID:0:4}"
-          echo "${AWS_BUCKET_KEY_NAME}"
-          echo "${AWS_BUCKET_NAME}"
-          echo "${AWS_COUNT_ID}" | grep -E '^[0-9]{12}$'
-          echo "${AWS_ROLE:0:13}"  # debería ser: arn:aws:iam::
-          echo "Longitud del AWS_REGION: ${#AWS_REGION}"
-          echo "Longitud del AWS_ACCESS_KEY_ID: ${#AWS_ACCESS_KEY_ID}"
-          echo "Longitud del AWS_BUCKET_KEY_NAME: ${#AWS_BUCKET_KEY_NAME}"
-          echo "Longitud del AWS_BUCKET_NAME: ${#AWS_BUCKET_NAME}"
-          echo "Longitud del AWS_COUNT_ID: ${#AWS_COUNT_ID}"
-          echo "Longitud del AWS_ROLE: ${#AWS_ROLE}"
-          echo "Longitud del AWS_SECRET_ACCESS_KEY: ${#AWS_SECRET_ACCESS_KEY}"
-          echo "Longitud del CLOUDFLARE_EMAIL: ${#CLOUDFLARE_EMAIL}"
-          echo "Longitud del CLOUDFLARE_TOKEN: ${#CLOUDFLARE_TOKEN}"
-          echo "Longitud del SSH_PRIVATE_KEY: ${#SSH_PRIVATE_KEY}"
-        env:
-          AWS_REGION : ${{ secrets.AWS_REGION }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
-          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
-          AWS_COUNT_ID: ${{ secrets.AWS_COUNT_ID }}
-          AWS_ROLE: ${{ secrets.AWS_ROLE }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
-          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+
       - name: Configure AWS credentials from AWS account
         uses: aws-actions/configure-aws-credentials@v1
         with:
           role-to-assume: ${{ secrets.AWS_ROLE }}
           aws-region: ${{ secrets.AWS_REGION }}
           role-session-name: GitHub-OIDC-TERRAFORM
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: arn:aws:iam::${{ secrets.AWS_COUNT_ID }}:role/github-oidc-terraform-aws-tfstates-role
-          aws-region: ${{ secrets.AWS_REGION }}
-      - name: Check AWS Identity
-        run: aws sts get-caller-identity
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.2.5
+
       - name: Terraform fmt
         id: fmt
         run: terraform fmt -check
         continue-on-error: true
+
       - name: Terraform Init
         id: init
         env:
           AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
           AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
         run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
+
       - name: Terraform Validate
         id: validate
         run: terraform validate -no-color
+
       #- name: Terraform Plan
        # id: plan
        # run: terraform plan -no-color
        # if: github.event_name == 'pull_request'
        # continue-on-error: true
+
       - uses: actions/github-script@v6
         if: github.event_name == 'pull_request'
         env:
@@ -104,26 +67,36 @@ jobs:
             #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
             #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
             <details><summary>Validation Output</summary>
+
             \`\`\`\n
             ${{ steps.validate.outputs.stdout }}
             \`\`\`
+
             </details>
+
             #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+
             <details><summary>Show Plan</summary>
+
             \`\`\`\n
             ${process.env.PLAN}
             \`\`\`
+
             </details>
+
             *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: output
             })
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+
+      #- name: Terraform Plan Status
+       # if: steps.plan.outcome == 'failure'
+       # run: exit 1
+
       - name: Terraform Apply
         if: github.ref == 'refs/heads/main' && github.event_name == 'push'
         run: terraform apply -auto-approve -var "ssh_private_key=${{ secrets.SSH_PRIVATE_KEY }}" -var "aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
